config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comparator/index'
  root 'comparator#index'
  post 'create', to: 'comparator#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comparator.rb
# frozen_string_literal: true

require 'json-diff'
require 'json'

class Comparator < ApplicationRecord
  attr_accessor :fileContent1
  attr_accessor :fileContent2
  validates :jsonfile1, :jsonfile2, presence: true
  before_save :compute_values

  private
    def compute_values
      firstJson = JSON.parse(fileContent1.read)
      secondJson = JSON.parse(fileContent2.read)
      computedJsonDiff = JsonDiff.diff(firstJson, secondJson)
      self.diff = !computedJsonDiff.length.zero? ? computedJsonDiff : nil
      self.equal = diff.nil?
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comparator_controller.rb
# frozen_string_literal: true

class ComparatorController < ApplicationController
  def index
    @comparator = Comparator.new
  end

  def create
    @comparator = Comparator.new
    @comparator.jsonfile1 = !params[:jsonfile1].nil? ? params[:jsonfile1].original_filename : nil
    @comparator.jsonfile2 = !params[:jsonfile2].nil? ? params[:jsonfile2].original_filename : nil
    @comparator.fileContent1 = params[:jsonfile1]
    @comparator.fileContent2 = params[:jsonfile2]

    if @comparator.save
      logger.debug "The files are equal: #{@comparator.equal}, file 1:#{@comparator.jsonfile1}, file 2:#{@comparator.jsonfile2}"
      @equal = @comparator.equal
      @diff = @comparator.diff
      render 'result'
    else
      render 'index'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comparator_helper.rb
# frozen_string_literal: true

module ComparatorHelper
end

app/views/comparator/index.html.erb
<h1>JSON Files comparator</h1>

<% if !@comparator.errors.empty? %>
   <div class = "alert alert-error">
      <ul>
         <% @comparator.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>
 <div class="container">
   <%= form_tag({:controller => :comparator, :action => :create}, {:multipart => true, :method => :post}) do |f| %>
    <div class="form-group row">
    <label class="control-label"  for="firstFileUpload">First file:</label>
    <div class="col-sm-10">
       <%= file_field_tag 'jsonfile1', accept: 'application/JSON,  text/plain' %>
    </div>
    <label class="control-label" for="firstFileUpload">Second file:</label>
    <%= file_field_tag 'jsonfile2', accept: 'application/JSON, text/plain' %>
   </div>
    <%= submit_tag "Compare!!", class: "btn btn-primary"  %>
  <% end %>
 <div>

app/views/comparator/result.html.erb
<h2> The files are
 <% if @equal == false %>
   <b>not</b>
 <% end %>
 equal
 </h2>
 <% if  @equal == false %>
   <b> Differences:</b>
   <input type="text" value="<%= @diff %>" class="text-description" readonly >
 <% end %>

<%= button_to "Back", comparator_index_path, method: :get, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileComparator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>